const tags = [
  ["linux", "!text-ctp-yellow"],
  ["typescript", "!text-ctp-blue"],
  ["hackathon", "!text-ctp-green"],
  ["neovim", "!text-ctp-green"],
  ["IT", "!text-ctp-mauve"],
  ["laptop", "!text-ctp-blue"],
  ["astro", "!text-ctp-red"],
  ["test", "!text-ctp-orange"],
  ["tech-stack", "!text-ctp-blue"],
  ["gamedev", "!text-ctp-sky"],
  ["snake", "!text-ctp-lavender"],
  ["fediverse", "!text-ctp-green"],
  ["mastodon", "!text-ctp-mauve"],
  ["devlog", "!text-ctp-red"],
  ["this", "!text-ctp-orange"],
  ["rust", "!text-ctp-orange"],
  ["C", "!text-ctp-blue"],
  ["low-level", "!text-ctp-red"],
  ["emulation", "!text-ctp-green"],
  ["langdev", "!text-ctp-orange"],
  ["parsing", "!text-ctp-mauve"],
  ["compilers", "!text-ctp-lavender"],
  ["poetry", "!text-ctp-orange"],
  ["terza-rima", "!text-ctp-lavender"],
];

export default tags;
