const tags = [
  ["linux", "yellow"],
  ["typescript", "blue"],
  ["hackathon", "green"],
  ["neovim", "green"],
  ["IT", "mauve"],
  ["laptop", "blue"],
  ["astro", "red"],
  ["test", "orange"],
  ["tech-stack", "blue"],
  ["gamedev", "sky"],
  ["snake", "lavender"],
  ["fediverse", "green"],
  ["mastodon", "mauve"],
  ["devlog", "red"],
  ["this", "orange"],
  ["rust", "orange"],
  ["C", "blue"],
  ["low-level", "red"],
  ["emulation", "green"],
  ["langdev", "orange"],
  ["parsing", "mauve"],
  ["compilers", "lavender"],
  ["poetry", "orange"],
  ["terza-rima", "lavender"],
  ["reading", "green"],
  ["goals", "rosewater"],
  ["storytelling", "green"],
];

export default tags;
